name: Build (Artifacts)

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    DART_SDK: beta
    INPUT_PATH: src/main.dart
    EXE_NAME: fuyu
    OUTPUT_EXE_PATH: bin/fuyu

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macOS-latest
        steps:
            - uses: actions/checkout@v2

            - uses: dart-lang/setup-dart@v1
              sdk: ${{ env.DART_SDK }}

            - name: 🚧 Do prerequisites
              run: |
                  dart pub get
                  dart run ./cli/generate_meta.dart

            - name: 👷 Build executable
              run: dart compile exe -o ${{ env.OUTPUT_EXE_PATH }} ${{ env.INPUT_PATH }}

            - name: 🚀 Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ env.EXE_NAME }}-${{ matrix.os }}
                  path: ${{ env.OUTPUT_EXE_PATH }}
