name: Code Analysis

on:
    push:
        branches:
            - main
            - next
        paths:
            - "cli/**"
            - "src/**"
    pull_request:
        branches:
            - main
            - next
        paths:
            - "cli/**"
            - "src/**"
    workflow_dispatch:

jobs:
    dart-analyze:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: dart-lang/setup-dart@v1

            - name: 🚧 Do prerequisites
              run: |
                  dart pub get
                  dart run ./cli/generate_meta.dart

            - name: 🩺 Check code format
              run: dart format --output=none --set-exit-if-changed .

            - name: 🩺 Analyze code
              run: dart analyze
